atleta=input("nome do atleta:")
p_salto= float(input("primeiro salto:"))
s_salto= float(input("segundo salto:"))
t_salto=float(input('terceiro salto:'))
qua_salto=float(input('quarto salto:'))
qui_salto= float(input('quinto salto:'))
print('Resultado final:' + (atleta))
print('Saltos:', p_salto,'-', s_salto,'-', t_salto,'-', qua_salto,'-',qui_salto)
soma= str ((p_salto+ s_salto+ t_salto+qua_salto+qui_salto)/ 5)
print('A media de so saltos foi: ',soma)
